
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.111:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
server:
  port:8888
spring:
  application:
    name:user-server
