server:
  port: ${PORT:8888}
spring:
  application:
    name: user-service
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://192.168.0.111:8710}
      discovery:
        enabled: true
        serviceId: user-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.111:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
